export enum NOTIFICATION_EVENT {
  THRESHOLD_REACHED = 'THRESHOLD_REACHED',
  CHARGE_ABORTED = 'CHARGE_ABORTED',
  LOG_FINISHED = 'LOG_FINISHED',
  CHARGE_REMINDER = 'CHARGE_REMINDER',
  QR_CHARGE_REQUEST = 'QR_CHARGE_REQUEST',
}