name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 22.x]
        mongodb-version: ['7.0', '8.0']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: evnotify
          mongodb-password: evnotify
          mongodb-db: evnotify

      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          DATABASE_URI: mongodb://evnotify:evnotify@127.0.0.1:27017/evnotify?authSource=admin
